plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':application')
    implementation project(':infrastructure')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.h2database:h2'
}
