plugins {
    id 'org.springframework.boot'
}

dependencyManagement {
    dependencies {
        dependency 'org.apache.groovy:groovy:4.0.22'
        dependency 'org.apache.groovy:groovy-json:4.0.22'
        dependency 'org.apache.groovy:groovy-xml:4.0.22'
    }
}

dependencies {
    implementation project(':application')
    implementation project(':infrastructure')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework:spring-jdbc'
    testImplementation 'org.springframework:spring-tx'
    testImplementation 'io.rest-assured:rest-assured:5.5.6'
    testRuntimeOnly 'com.h2database:h2'
}
